### ISSUE TITLE
Publish incorrect after renaming img folder

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/coding-blog#10]
I [renamed the `img` folder to `images`](https://github.com/bender2k14/tyson-williams-blog/commit/2604e748bfc7ca2105e945209a947e9de8fb0f08).  I found all those references by searching within all files in the repo for `img`.  I didn't think I missed any.

Everything worked locally, but the publish did not.  The files still published to same `img` folder.

Is there something in the publishing process that is hardcoded to use `img`?

**Comment by loreanvictor** [comment]
yeah it seems you missed [`.codedoc/config.ts`](https://github.com/bender2k14/tyson-williams-blog/blob/c07efbd58b52d2097e74e31db3e676ba81ab6bf3/.codedoc/config.ts#L28-L33). you basically need to tell `coding.blog` publishing service [which asset files to copy from your repo and pull alongside the distributed version of your blog](https://connect-platform.github.io/coding-blog-plugin/assets), similar to how you need to [copy your images in the GitHub Action](https://github.com/bender2k14/tyson-williams-blog/blob/c07efbd58b52d2097e74e31db3e676ba81ab6bf3/.github/workflows/deploy-to-gh-pages.yml#L22-L23).

**Comment by TysonMN** [comment]
Oh, yes...of course.  Thanks pointing out my mistake.  I am certain that I made that change.  I think I forgot to save it before commiting.
