### ISSUE TITLE
Display publish status on account/blog

### ISSUE THREAD

**Issue by loreanvictor** [CONNECT-platform/coding-blog#11]
courtesy to nice APIs provided by @must , it is now possible to give direct feedback to blog authors about the publish status of their blog beyond sending a success/failure email. these APIs should be adopted on the UI to provide direct realtime information on publish status of a particular blog.

**Comment by TysonMN** [comment]
Where can I go to see this?

**Comment by loreanvictor** [comment]
[the blog management page](https://coding.blog/account/blog). Note that the APIs right now allow for one publish per 5 minutes or so, which is typically fine but in case of testing might be a bit of an inconvenience (we are actually switching from that debounce strategy, but that will be deployed later).

**Comment by must** [comment]
@loreanvictor Publishing is now allowed with one restriction: one running build at a time. If a build status gets stuck on "running" for some reason then a new build can be launched in 5 minutes. This should be a very rare occurrence in some potential edge cases. Will do more work to improve on this as we scale further.
