### ISSUE TITLE
Old files remain deployed

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/coding-blog#12]
I renamed my `img` folder to `images`.  The images are now accessible via that directory, but they are still available at the previous one as well.

- New URL, expected to work and does
    - https://tysonwilliams.coding.blog/images/cb-banner-dark.svg
- Old URL, expected to 404 but doesn't
    - https://tysonwilliams.coding.blog/img/cb-banner-dark.svg

Alternatively, looking at [my `gh-pages` branch](https://github.com/bender2k14/tyson-williams-blog/tree/gh-pages) shows both the `img` and `images` folders.

I expected old files like those in `img` to be deleted from `gh-pages` when I push to `master` commits that removed those files (and all the files inside them).

Is the fix to delete the pre-existing files in [the `run` step of the GitHub deploy script](https://github.com/CONNECT-platform/coding-blog-boilerplate/blob/master/.github/workflows/deploy-to-gh-pages.yml#L14-L23)?

I tried removing files from `dist` with the command `rm -rf dist/`, but [my deploy fails](https://github.com/bender2k14/tyson-williams-blog/actions/runs/136313344).

**Comment by loreanvictor** [comment]
for cleaning up your `gh-pages` build, I suspect the cleanest way is to switch to `gh-pages` branch locally, remove files you do not want on the branch anymore (and ensure codedoc doesn't generate them again), and then push the branch.

on `coding.blog`, this is an issue and currently there is no mechanism for cleaning up old files. it is on our roadmap, so I'll keep this issue open for monitoring the release of that feature.

@must

**Comment by TysonMN** [comment]
> for cleaning up your `gh-pages` build, I suspect the cleanest way is to switch to `gh-pages` branch locally, remove files you do not want on the branch anymore (and ensure codedoc doesn't generate them again), and then push the branch.

I removed all the files in the `img` folder of [my `gh-pages` branch](https://github.com/bender2k14/tyson-williams-blog/tree/gh-pages), pushed that branch, then triggered another deploy (by pushing some "no-op" change to `master`), but https://tysonwilliams.coding.blog/img/cb-banner-dark.svg still exists (...as long as I am not being tricked by a cache).

Whatever.  I don't really like having to do that anyway.  I would rather wait for an automated solution (but this might help in creating the automated solution, so I thought I would share it).

**Comment by loreanvictor** [comment]
> > for cleaning up your `gh-pages` build, I suspect the cleanest way is to switch to `gh-pages` branch locally, remove files you do not want on the branch anymore (and ensure codedoc doesn't generate them again), and then push the branch.
> 
> I removed all the files in the `img` folder of [my `gh-pages` branch](https://github.com/bender2k14/tyson-williams-blog/tree/gh-pages), pushed that branch, then triggered another deploy (by pushing some "no-op" change to `master`), but https://tysonwilliams.coding.blog/img/cb-banner-dark.svg still exists (...as long as I am not being tricked by a cache).

That solution is for your GitHub pages site not for `coding.blog`, which is an independent deploy. For example, while your GitHub pages deploys contents of `gh-pages` branch, `coding.blog` deploys contents of your main branch, which can be completely different.

Anyways, as mentioned before, currently there is no way to clear files from your `coding.blog` (but there is for GitHub pages), which is why this issue is open.

**Comment by must** [comment]
This relates to the diff system that we will implement. Then we will be able to update the published files to reflect the latest published built files (i.e. removing ones that don't result from the build any more).
