### ISSUE TITLE
Recommended solution for comments

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/coding-blog#13]
I would prefer to allow people to comment on my blog and have those comments included on the same page as the blog.

Will coding.blog suggest one or more ways to handle comments?

Here are two approaches that I have seen.
1. Have commenters submit PRs that add their comments to the file containing the blog post.
2. Use [utterances](https://utteranc.es/), which uses an issue on the backing GitHub repo to store the comments.

I think I like the second approach better.

**Comment by loreanvictor** [comment]
> Will coding.blog suggest one or more ways to handle comments?

Depends. Right now this is not a priority, and I personally lean towards the community coming up with nice solutions on their own, which would perhaps be a custom codedoc plugin.

However, if there is disparity in adoption or difficulty of use for a lot of people, it might be a good idea to also provide some solution via the default plugin, to ensure a level-playing field. The maximum quality and capabilities of a blog shouldn't be limited (this is not Medium), but the minimum quality should be high enough for a generally good experience for everyone (and every blog).

> Here are two approaches that I have seen.
>
> Have commenters submit PRs that add their comments to the file containing the blog post.
> Use utterances, which uses an issue on the backing GitHub repo to store the comments.

They both seem pretty nice, however I am hesitant towards the default solution (or the recommended solution) being exclusive to GitHub.

P.S. I am also unsure of effectiveness of traditional comment threads on blogs, specifically technical blogs. There is a necessity for means of communication, however it might be possible that less conventional solutions (like Q&As with author on specific points on a blog) might be more useful.

**Comment by loreanvictor** [comment]
Anyways I will keep this issue open for now and pin it, to maintain an open discussion on the topic.
