### ISSUE TITLE
Missing URL replaced by 404 URL on coding.blog-deployed site

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/coding-blog#14]
Going to https://coding.blog/asdf shows the 404 page but leaves the URL unchanged.
![2020-06-15_23-11-55_131_chrome](https://user-images.githubusercontent.com/34664007/84731282-02623a80-af5e-11ea-9c53-69a20cd9252b.png)

Going to http://localhost:3000/asdf when locally hosting my blog shows the 404 page but leaves the URL unchanged.
![2020-06-15_23-12-50_132_chrome](https://user-images.githubusercontent.com/34664007/84731327-245bbd00-af5e-11ea-8201-045c5784fa15.png)

However, going to https://tysonwilliams.coding.blog/asdf shows the 404 page _AND_ changes the URL to https://tysonwilliams.coding.blog/404.
![2020-06-15_23-13-10_133_chrome](https://user-images.githubusercontent.com/34664007/84731379-50773e00-af5e-11ea-96fa-8eb9f834cf8b.png)

Why is the URL being replaced?  I don't want this to happen.  It makes it more difficult to debug why the 404 is happening.  How can I make it so the URL is not replaced?

**Comment by must** [comment]
Due to the current way we handle CDN requests, it was implemented based on a redirect. I will look into how we can improve it towards having no redirects but rather a 404 response with the proper not found html page.

**Comment by TysonMN** [comment]
And do you understand why coding.blog and tysonwilliams.coding.blog behave differently?

**Comment by must** [comment]
@TysonMN Yes, Coding.blog is handled through Github Pages which already provides this behaviour as you want it.
