### ISSUE TITLE
View files deployed to coding.blog site

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/coding-blog#16]
I would find it helpful for debugging if I could see the files that have been deployed to my site hosted by coding.blog.

Quoting from https://github.com/CONNECT-platform/coding-blog/issues/15#issuecomment-644549402
> Your `coding.blog` always deploys contents of the default branch of your repository (which is master).

Seem right as a first approximation.  Then the next approximation is to say that the files generated during `codedoc install` and `codedoc build` are also deployed.

However, I get the impression that this is still not the full picture.  I will elaborate on this soon in a new issue that will link to this one.

**Comment by loreanvictor** [comment]
yep its a nice thing to display those files, also I suspect the explanation on how coding.blog handles assets could be improved. specifically, a more prominent link to [this page](https://connect-platform.github.io/coding-blog-plugin/assets), plus further explanation on the page should be handy.

**Comment by must** [comment]
I'll add this to the roadmap. It would be a nice to have: to provide the user with feedback on changes to last deployed build (which files were added, removed, or modified).
