### ISSUE TITLE
File missing on coding.blog-deployed site

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/coding-blog#17]
(In a previous "[version of this issue](https://github.com/CONNECT-platform/coding-blog/issues/15)", I misunderstood the relationship between the `gh-pages` branch and my site being hosted on `conding.blog`.  Short answer: there is no relation.)

When locally hosting my site, http://localhost:3000/images/TysonWilliams.jpg exists.
![2020-06-16_08-18-46_135_chrome](https://user-images.githubusercontent.com/34664007/84779560-29def480-afaa-11ea-81f9-e104499dd342.png)

But https://tysonwilliams.coding.blog/images/TysonWilliams.jpg returns 404.

Why is that?

While debugging this issue, I thought it would be useful if
- previously deployed files where removed (issue https://github.com/CONNECT-platform/coding-blog/issues/12),
- the URL of a missing resource remained in the address bar (issue https://github.com/CONNECT-platform/coding-blog/issues/14), and
- I could see the files deployed to coding.blog (issue https://github.com/CONNECT-platform/coding-blog/issues/16).

I am out of ideas now.  What other debugging techniques could I use to better understand the differences between my site when locally hosted vs when hosted by `coding.blog`?

**Comment by loreanvictor** [comment]
curious. to the best of my knowledge, the paths you specify to coding-blog-plugin are the assets that coding.blog will pick up and deploy alongside your blog, which should mean that `src/assets/images/TysonWilliams.jpg` should be at least accessible, but I cannot access that either.

@must any ideas? is this a bug?

**Comment by must** [comment]
This seems to be a bug with nested folders. I'm working on fixing it.

**Comment by must** [comment]
@bender2k14 This should now be fixed. I launched a build job for your blog. All relevant files should now be accessible.

**Comment by loreanvictor** [comment]
@bender2k14 just a heads up, with this fix you would get the image on coding.blog on `/src/assets/images/TysonWilliams.jpg` instead of `/images/TysonWilliams.jpg`. you can for now change your local config to mirror this behavior, but [this issue](https://github.com/CONNECT-platform/coding-blog/issues/18) would also allow you to specify mappings for your assets deployed on coding.blog, which would allow you to achieve what you are looking for.

**Comment by TysonMN** [comment]
Thanks guys :)
