### ISSUE TITLE
Correctly link to Light/Dark image

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/coding-blog#19]
The [homepage of coding.blog](https://coding.blog/) starts with a big banner image that varies slightly between light mode and dark mode.

- When in light mode, the image at `https://coding.blog/banner.svg` is displayed but right-clicking (in Google Chrome) and selecting "Copy image address" copies `https://coding.blog/banner-dark.svg` onto the clipboard.
- The opposite happens in dark mode: the displayed image is `https://coding.blog/banner-dark.svg` but the addressed copied is `https://coding.blog/banner.svg`.

**Comment by loreanvictor** [comment]
Anyways this belongs to **CODEDOC**, and while for more major issues I would keep them open on all affected repositories to monitor the situation / issue updates, I will close this issue since this one is minor.
