### ISSUE TITLE
Only publish on pushes to master

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/coding-blog#30]
I just noticed that if I push any branch to [my repo](https://github.com/TysonMN/tyson-williams-blog), then my webhook is triggered and my site is redeployed.  My intention is that my site is only redeployed when I push to `master`.

Reviewing the [coding.blog webhook documentation](https://coding.blog/knowledge/publish-webhook) and looking at the options available in the push event of GitHub's webhook, I don't think I can make this webhook any more refined / granular.  However, I think coding.blog could make an adjustment.

GitHub's webhook documentation for the [push event](https://developer.github.com/webhooks/event-payloads/#push) says that it includes a [payload object](https://developer.github.com/webhooks/event-payloads/#webhook-payload-object-33).  One of the keys in that payload is `ref`, which is described as
> The full `git ref` that was pushed.

The two examples given in the document are
- `refs/heads/master` and
- `refs/tags/simple-tag`.

The [coding.blog documentation on publishing](https://coding.blog/knowledge/setting-up-a-blog#publishing) says
> Our build servers will clone the _master branch_ of your repo...

So I think the current behavior of coding.blog is to publish the site defined by the `master` branch on any push event even though the payload object might show that the `master` branch didn't change.

Can the publishing process of coding.blog be changed to only publish a site when the payload object sent with the webhook shows that the `master` branch was changed?

**Comment by loreanvictor** [comment]
That would be a good idea, at least it will save us some builds. it is notable that as it stands the publish system doesn't really look at the payload passed to the publish webhook, as it is not designed specifically for use with GitHub only. This means that in the end we should at least be supporting all major version control service providers in the same manner, though we can take on that in an incremental manner (for example, starting with GitHub).

@must any thoughts on this?

**Comment by must** [comment]
Agreed. Just need some time to work on this and implement the change. In the future, we can also think of supporting other branches for publishing purposes but for now it should be enough to only consider master.

**Comment by TysonMN** [comment]
FWIW, here is an idea.

I know it is possible to trigger a GitHub Action only on a push to `master` (for example, [this action that I created](https://github.com/hedgehogqa/fsharp-hedgehog/blob/2767e24104bad062a041763781e8469c8b7dbd7d/.github/workflows/dotnet-core.yml#L3-L5)).  So then it suffices to call the webhook as a step in the GitHub action.  Seems like something that should be possible, but I have not looked into that.

**Comment by must** [comment]
We can also add support on our backend to read the Github webhook call request and decide to publish or not depending on the branch / type of action (i.e. commit on master). And then we can also potentially enable you to choose which branch to push from.

**Comment by TysonMN** [comment]
Great work! :)

FWIW, a workaround (either for GitHub before your recent change or for a different site) is to create a fork of the repo and push branches there.  I have been doing that lately with a private fork to hold onto draft posts.
