### ISSUE TITLE
Separate staging and live sites

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/coding-blog#31]
This is a spin off of https://github.com/CONNECT-platform/codedoc/issues/70#issuecomment-692075458.

Sometimes there are differences between my live/deployed site hosted at `coding.blog` and when I locally host my site.  To make it easier to test and troubleshoot these issues, it would be great if there were two places to which I could deploy my site.  For example, they could either be separate dedicated staging and live sites or two separate staging and live sites but there is a simple switch that controls which one is which.  I know the second configuration by the name [blue/green deployment](https://martinfowler.com/bliki/BlueGreenDeployment.html).

Would it be possible to one day have separate staging and live sites?

**Comment by must** [comment]
We would consider this for the future. A preview version of the blog + some simple deployment version management functionality (with roll-back capability etc...).

**Comment by loreanvictor** [comment]
You can already do this in multiple ways:

- Method 1:
  - Remove the hook between GitHub and coding.blog.
  - Enable GitHub pages
  - Now your GitHub pages version can act as the "staging" version, and the publish button on blog management page will basically "publish to production" (to the actual version).

- Method 2:
  - Enable GitHub pages, but modify the workflow so that it is built from a different branch (say staging).
  - Now your staging branch is basically the staging state of your blog (can be previewed on GitHub pages),
    and merging it into master would be equivalent of putting it on prod.

Generally speaking, the repos are version controlled with Git to allow all of this "version management" intrinsically, so I am personally against any further layer of version control on top of that and would prefer all version management to happen in git itself.

**Comment by TysonMN** [comment]
Using GitHub pages is a good idea, but it also just kicks the can down the road a bit.  There is already [explicit differences between hosting on `coding.blog` and GitHub pages](https://github.com/CONNECT-platform/coding-blog-boilerplate/blob/9cc9cc78f3785540f6cff1a2de2c297815433e74/.codedoc/config.ts#L17-L19), and there are probably many implicit differences.  For example, maybe GitHub pages has always served files with names that start with a period while this behavior didn't intentionally exist for `coding.blog` until recently, and I have yet to verify the new intentional behavior (c.f. https://github.com/CONNECT-platform/codedoc/issues/70).

Another idea (that I mentioned in https://github.com/CONNECT-platform/codedoc/issues/70#issuecomment-694201346) is to have a page on my site with no in-links.  I was even thinking of using a GUID for its name.  Then for all practical purposes, no one will ever find that page.  The goal here is just to not affect normal visitors to my site.  I don't care that GitHub would "clearly" show this secret testing page.

_Edited to add:_
I forgot to mention the limitation of this approach.  It allows testing page-specific behavior in isolation.  However, changes to configuration are site wide, so those changes still don't have a good way to tested in the live environment.

**Comment by loreanvictor** [comment]
> There is already explicit differences between hosting on coding.blog and GitHub pages, and there are probably many implicit differences. 

Valid point. Perhaps we should add the ability to also deploy another branch of a repo, either on a sub-url or another subdomain (such as tysonwilliams.staging.coding.blog). It would mean that the "version control" is still bound directly to git (rollbacks, merging, etc), but also we have a perfectly identical "staging" environment for the deployments.

**Comment by must** [comment]
@loreanvictor @TysonMN Random question: Any SEO implications of having duplicate content on separate URLs / Domains?

**Comment by loreanvictor** [comment]
> @loreanvictor @TysonMN Random question: Any SEO implications of having duplicate content on separate URLs / Domains?

might be. I mean google might just index the staging subdomain for example.

right now, the solution for that would be for authors to add canonical URLs manually. perhaps we can later automate that a bit?

**Comment by must** [comment]
Then it should be indicated to the crawlers that they shouldn't index the staging subdomain. That should solve the issue. Just noting it down for future reference.

**Comment by TysonMN** [comment]
Sounds good to me. FYI, I don't know that nun about SEO.
