### ISSUE TITLE
Cannot publish

### ISSUE THREAD

**Issue by uloco** [CONNECT-platform/coding-blog#37]
I am trying to publish my first blog post for a couple of days now and always get an error that "oops, something went wrong". I am using the coding.blog publish webhook button on the page.
Any ideas?

**Comment by must** [comment]
Hi there, it looks like we have a problem with our publishing service. We're looking into it and we'll give you an update as soon as possible!

**Comment by must** [comment]
It should now work as usual. Sorry for the inconvenience!
