### ISSUE TITLE
DNS record issues

### ISSUE THREAD

**Issue by loreanvictor** [CONNECT-platform/coding-blog#42]
`api.coding.blog` and `*.coding.blog` are not working at the time, which means sub-domains are not accessible momentarily. We are working on the issue.

**Comment by must** [comment]
Updated the records. Should work again once DNS propagates properly.

**Comment by TysonMN** [comment]
My site works again. Good work.

**Comment by loreanvictor** [comment]
Ok I'm going to pin this for 24 hours (since DNS propagation for some folks might take that long) and close it afterwards.
