### ISSUE TITLE
Question: Can I make a workflow for this repository for checks?

### ISSUE THREAD

**Issue by im-coder-lg** [CONNECT-platform/coding-blog#49]
hey @loreanvictor, I was checking my blog repository when I got curious for GitHub Actions Checks. Like, there are some repos that have a Node project and they use GH Actions as checks. So, I wondered, this is a space that gets PRs, so why not make a `checks` workflow that can check if there is errors? Just curious if you really need it here, if you accept, I can start the work on that.

**Comment by im-coder-lg** [comment]
pinging @loreanvictor

**Comment by im-coder-lg** [comment]
Ping @loreanvictor can you say your opinion?

**Comment by loreanvictor** [comment]
@coder-lg sorry for the delayed response, day job is leaking extensively into weekends these days 😅

Of course, any sort of actions that would conduct checks and tests would be neat. However, this repo specifically is focused on the static website, which means there aren't many checks and tests to be conducted to begin with (maybe testing the API? but that would need to be a recurring action not one that is triggered by a PR). Another cool option would be registering for domains via creating an issue on this repository (alongside the current mechanism). It is not needed by any means, but it would be pretty cool.

On this front, CODEDOC itself is in dire need of testing and coverage honestly. It is a much bigger and more complex repo, and it has zero coverage right now unfortunately. It does utilize other libs for key functionality, some of which do have good automated testing (and some other, again unfortunately, don't). It might also be a good idea to start with coverage for side tools (such as the CLI). Fair note is that this would digress from just adding some actions and would be mostly about writing test coverage.

**Comment by im-coder-lg** [comment]
What I meant was a NodeJS check sort of thing, since this is an NPM-based project, I can add the lines:
```bash
npm i -g @codedoc/cli
codedoc install
codedoc build
```
It does work at my repository.

**Comment by im-coder-lg** [comment]
I tried it actually, and decided to ask.

**Comment by loreanvictor** [comment]
something like this?

https://github.com/CONNECT-platform/coding-blog/blob/master/.github/workflows/deploy-to-gh-pages.yml

**Comment by im-coder-lg** [comment]
somewhat like [`this`](https://github.com/coder-lg/coder-lg-blog-codedoc/blob/master/.github/workflows/codedoc.yml)

**Comment by im-coder-lg** [comment]
If it fails, it will show a fail part. Build is almost like `serve` except it builds the entire site for deploying it on Netlify or maybe Vercel. So, why not use it there?

**Comment by im-coder-lg** [comment]
So, I have a fresh idea. I will put the workflow in the `gh-pages` branch. Anything pushed there will be test-built and if it fails, YOU will get a mail.

**Comment by im-coder-lg** [comment]
It will pinpoint the file causing the errors mainly :)

**Comment by loreanvictor** [comment]
The original action I mentioned basically does this second idea:

- it uses `codedoc build` to build the docs
- it pushes them to `gh-pages` branch
- it will (well, github will) notify you when this fails.

It is (perhaps) a good idea to also run `codedoc build` on PRs, to ensure nothing is wrong. It would not be wise to push to `gh-pages` branch on each PR though.

Am I missing something?

**Comment by im-coder-lg** [comment]
> The original action I mentioned basically does this second idea:
> 
> * it uses `codedoc build` to build the docs
> * it pushes them to `gh-pages` branch
> * it will (well, github will) notify you when this fails.
>
Ookayyy...


> It is (perhaps) a good idea to also run `codedoc build` on PRs, to ensure nothing is wrong. It would not be wise to push to `gh-pages` branch on each PR though.

Yup, I say that it is good to run `codedoc build` on PRs to make sure the files are FREE of typos.



> Am I missing something?

Nope, you are not missing anything. Why not we add that workflow **only** to the PRs?

**Comment by im-coder-lg** [comment]
That would mean that the workflow aka. pr-verify.yml would check only the PRs, so that the original workflow that DEPLOYS to gh-pages would be perfect.

**Comment by im-coder-lg** [comment]
Why not try that?

**Comment by loreanvictor** [comment]
yep, sure thing. I was just trying to understand precisely your suggestion here.

**Comment by im-coder-lg** [comment]
> yep, sure thing. I was just trying to understand precisely your suggestion here.

dude, I figured it out on your last comment. I will learn or review one of my old GH Actions lessons, because I got some lines on one of them.

**Comment by im-coder-lg** [comment]
It was you who gave the idea without knowing it too. Your workflow is on push to master. Mine is for all the PRs.

**Comment by im-coder-lg** [comment]
Well, just figured something out. I will add it to `master`. Mostly, it is checks, but it doesn't deploy to `gh-pages`. Just curious, @loreanvictor does the codedoc cli have a `codedoc check` command where it checks if each file can be built?

**Comment by loreanvictor** [comment]
> does the codedoc cli have a codedoc check command where it checks if each file can be built?

That would be `codedoc build`. It tries to build each file, and if it fails it will exit with an error status code. Is there a different behavior you expect from a potential `codedoc check` command?

**Comment by im-coder-lg** [comment]
Well, I thought that `codedoc check` was mainly for checks but I realized it was for somethig else. Can I try this(workflow) and make it into a PR?

**Comment by loreanvictor** [comment]
of course, it'd be much appreciated!

**Comment by im-coder-lg** [comment]
Okay @loreanvictor will add it soon.

**Comment by im-coder-lg** [comment]
Done, check #50

**Comment by loreanvictor** [comment]
merged, thanks a ton @coder-lg

**Comment by im-coder-lg** [comment]
Well, you helped in this too by giving an idea here.

**Comment by im-coder-lg** [comment]
Thanks for that 😊
