### ISSUE TITLE
Deployment errors on Vercel

### ISSUE THREAD

**Issue by im-coder-lg** [CONNECT-platform/coding-blog#52]
from #51 
the vercel.json is present, I have errors, the stylesheets aren't included, all errors :sweat_smile:

**Comment by im-coder-lg** [comment]
@loreanvictor can you help me on this issue?

**Comment by im-coder-lg** [comment]
please help me @loreanvictor

**Comment by loreanvictor** [comment]
@im-coder-lg sorry I have been so busy lately, perhaps @must can also take a look if you've got some time?

P.S. @im-coder-lg can you link the repo here for easier access?

**Comment by im-coder-lg** [comment]
Well, I'd like to know _how_ to configure Vercel to deploy the website and as well as how to include the stylesheets and JS files.
If anyone knows about that can they tell how to do it here?

**Comment by im-coder-lg** [comment]
> P.S. @im-coder-lg can you link the repo here for easier access?

Here: https://github.com/im-coder-lg/coder-lg-blog-codedoc

**Comment by loreanvictor** [comment]
If I recall correctly, @cupcakearmy figured out how to deploy codedoc to vercel initially.

**Comment by im-coder-lg** [comment]
Can you post any issue/article where he figured it out?

**Comment by cupcakearmy** [comment]
@im-coder-lg 
look at the docs i deploy on vercel https://github.com/cupcakearmy/autorestic/tree/master/docs

**Comment by im-coder-lg** [comment]
But how do you do it? You need configuration, right? Without Vercel configs you can't publish the website, right?

**Comment by im-coder-lg** [comment]
Still no stylesheets. I have bundles and asset files there which is needed(?). I need the stylesheets there. As of now, latest commit is: https://github.com/im-coder-lg/coder-lg-blog-codedoc/commit/47907853fb0eecd3ea5082faddef20c3dd8034cd

**Comment by cupcakearmy** [comment]
Maybe lets chat over on discord or telegram (same username), no need to clutter the issue here.

**Comment by im-coder-lg** [comment]
What about Gitter? I can't get a new account right now and I don't need Discord, so why not Gitter or something on the Matrix Protocol?

**Comment by cupcakearmy** [comment]
same username on gitter
