### ISSUE TITLE
Cannot set blog repo URLs to ones not ending with .git

### ISSUE THREAD

**Issue by loreanvictor** [CONNECT-platform/coding-blog#7]
Right now, there is a client side validation that ensures repo URLs end with .git, which wrongfully bars some proper git repositories.

Issue mentioned by @bentinata.

**Comment by loreanvictor** [comment]
according to @must , there is some server-side validation for this as well that is dependent on a third-party package.

**Comment by must** [comment]
@loreanvictor this has been fixed. URLs are now checked with a generic regex rather than a package that limits it with specific characters / .git extension at the end.

**Comment by loreanvictor** [comment]
the client-side validation is not disabled yet. will close this issue after it is.
