### ISSUE TITLE
Improvement to Author Information documentation

### ISSUE THREAD

**Issue by adammflax** [CONNECT-platform/coding-blog#8]
It took me a while to work out how Automatic Inference worked. I wrongly pressumed that it worked out of the box automagically. Prehaps there should be a sentence stating that the user needs to update the github information found in config.ts

**Comment by loreanvictor** [comment]
added further explanation on [the corresponding section of docs](https://connect-platform.github.io/coding-blog-plugin/author#automatic-inference) of [coding-blog-plugin](https://github.com/CONNECT-platform/coding-blog-plugin/).

feel free to re-open this issue if you think further explanation is required.
