### ISSUE TITLE
On choosing a good repo name

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/coding-blog#9]
The [Setting up a Blog page](https://coding.blog/knowledge/setting-up-a-blog#setting-up-a-blog) links to the [template fork page](https://github.com/CONNECT-platform/coding-blog-boilerplate/generate) page (with hypertext "using this template").  At first, I named my forked repo `blog`.  But after I cloned it, I didn't like this name, because the name of the repo is the default name of the folder (when cloned with GitKraken).  I want the folder name to be more descriptive, both for me and for anyone else that clones my repo, so I renamed it to `tyson-williams-blog`.

I don't think it's necessary to make a change based on this feedback, but I thought it could be helpful to share it anyway.  No worries if this is too minor, and the issue gets closed straight away.

If you did want to make a change, maybe provide a default suggestion for the blog name in the "Setting up a blog" page or maybe even auto-populate the text box for the blog name...if GitHub supports that.

**Comment by TysonMN** [comment]
A reasonable default/suggestion might be `{GitHub username}-blog` or maybe a different separating character like `.`.

**Comment by loreanvictor** [comment]
@bender2k14 I couldn't find any documentation on how to propose names for repositories that are being generated from a template. will add a hint to the blog management page though.
